baseurl = "https://www.howie6879.cn"
title = "老胡的储物柜"
canonifyurls = true
paginate = 6
languageCode = "en-us"
MetaDataFormat = "yaml"
theme = "Gemini"
googleAnalytics = "6MOOsWAEAomrK0SbuyIj5qHKPmawJXdNtiWbB-6DO3U" # Google 统计

[params]
  Keywords = ""
  Author = "howie6879"
  RecentPostCount = 8 
  Favicon = "/images/favicon.png"
  Intro = ["浮浮沉沉","努力就好"]
  SiteComments = false # 评论默认开启 单篇文章中可设置 dis_comments: true 来关闭评论
  CNZZ = "https://s5.cnzz.com/z_stat.php?id=1275251618&web_id=1275251618"
  
[params.comment]
  owner = "howie6879" 
  repo = "howie6879.github.io"
  client_id = "c7c56d99651604d9f431"
  client_secret = "c7ed7b7e268fb3fb3d8bc8ec68efa3510e7430d6"

[[params.social]]
  title = "Github"
  url = "https://github.com/howie6879"
  
[[params.social]]
  title = "Email"
  url = "mailto:xiaozizayang@gmail.com"

[[params.social]]
  title = "RSS"
  url = ""

[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -200
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = -180
[[menu.main]]
  name = "Friend"
  url = "/friend/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -160